// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hazard
List hazard(NumericVector y1, NumericVector y2, NumericVector lev, NumericVector wt);
RcppExport SEXP DStree_hazard(SEXP y1SEXP, SEXP y2SEXP, SEXP levSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lev(levSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP );
        List __result = hazard(y1, y2, lev, wt);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hazardl
List hazardl(NumericVector y1, NumericVector y2, NumericVector lev, int ind, NumericVector wt);
RcppExport SEXP DStree_hazardl(SEXP y1SEXP, SEXP y2SEXP, SEXP levSEXP, SEXP indSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lev(levSEXP );
        Rcpp::traits::input_parameter< int >::type ind(indSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP );
        List __result = hazardl(y1, y2, lev, ind, wt);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hazardr
List hazardr(NumericVector y1, NumericVector y2, NumericVector lev, int ind, NumericVector wt);
RcppExport SEXP DStree_hazardr(SEXP y1SEXP, SEXP y2SEXP, SEXP levSEXP, SEXP indSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lev(levSEXP );
        Rcpp::traits::input_parameter< int >::type ind(indSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP );
        List __result = hazardr(y1, y2, lev, ind, wt);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// lik
double lik(NumericVector S, NumericVector pi, NumericVector ncens, NumericVector nuncens);
RcppExport SEXP DStree_lik(SEXP SSEXP, SEXP piSEXP, SEXP ncensSEXP, SEXP nuncensSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type S(SSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type ncens(ncensSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nuncens(nuncensSEXP );
        double __result = lik(S, pi, ncens, nuncens);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
